### ISSUE TITLE
Make the "old" no-inject resource working properly

### ISSUE THREAD

**Issue by rsvoboda** [rsvoboda/resteasy-sse#2]
Getting NPE after @context changes in jsr370 branch.

```
11:13:04,264 ERROR [stderr] (Thread-181) javax.ws.rs.ProcessingException: java.lang.NullPointerException
11:13:04,265 ERROR [stderr] (Thread-181) 	at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.onNext(SseEventOutputImpl.java:116)
11:13:04,265 ERROR [stderr] (Thread-181) 	at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.onNext(SseEventOutputImpl.java:26)
11:13:04,265 ERROR [stderr] (Thread-181) 	at com.github.rsvoboda.sse.SseResource.lambda$greenHouseStatus$0(SseResource.java:34)
11:13:04,265 ERROR [stderr] (Thread-181) 	at java.lang.Thread.run(Thread.java:745)
11:13:04,265 ERROR [stderr] (Thread-181) Caused by: java.lang.NullPointerException
11:13:04,265 ERROR [stderr] (Thread-181) 	at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.onNext(SseEventOutputImpl.java:111)
11:13:04,266 ERROR [stderr] (Thread-181) 	... 3 more
```

Problem seems to be that I can't invoke SseEventOutputImpl.init() as the method is protected
https://github.com/asoldano/Resteasy/commit/8f2b13159b7bd544c13ef84b78517447ee5d2c76#diff-97c04cdfc0891675b26b1a572dba739cR42

**Comment by rsvoboda** [comment]
https://github.com/asoldano/Resteasy/pull/2
